FROM $(REGISTRY)/$(GOBUILD_NSBU_DOCKER_IMAGES_BUILDID)/ubuntu16.04-alias as cni-binaries

ADD xenial.sources.list /etc/apt/sources.list
ADD nsbu-xenial.list /etc/apt/sources.list.d/

RUN apt-get update && \
    apt-get install -y --no-install-recommends --allow-unauthenticated wget ca-certificates

# Leading dot is required for the tar command below
ENV CNI_PLUGINS="./host-local ./loopback ./portmap"

RUN mkdir -p /opt/cni/bin && \
    wget -q -O - https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz | tar xz -C /opt/cni/bin $CNI_PLUGINS


FROM registry.local/$(BUILDID)/openvswitch

LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
LABEL description="A Docker image to deploy the Antrea CNI. Requires the Antrea binaries to be built prior to building the image."

USER root

RUN apt-get update && apt-get install -y --no-install-recommends --allow-unauthenticated \
    ipset jq && \
    rm -rf /var/lib/apt/lists/*

COPY --from=cni-binaries /opt/cni/bin /opt/cni/bin

COPY build/images/scripts/* /usr/local/bin/
COPY bin/* /usr/local/bin/
