image: gobuild-container-registry.lvn.broadcom.net/cayman_go/vmware-go1.23-unified/9365edac4f02869d784100b5c5a8c52fd500bbfe/release/publish/infra/docker/ubuntu-amd64/1.23.2:ob-24343099

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache
  DOCKER_BUILDKIT: 1
  NO_PULL: 1

stages:
  - test

test-unit:
  stage: test
  script:
    - echo "Check if we can build e2e tests"
    - go test -c  -o /dev/null antrea.io/antrea/test/e2e
    - echo "Run unit tests"
    - make test-unit

check-codegen:
  before_script: []
  image: dockerhub.packages.vcfd.broadcom.net/antrea/codegen:kubernetes-1.31.1-build.1
  stage: test
  script:
    - ./ci/check-codegen.sh

check-manifest:
  before_script: []
  stage: test
  script:
    - ./ci/check-manifest.sh

# TODO: Enable Golang lint check and fix the lint errors
#check-lint:
#  stage: lint
#  script:
#    - make golangci

build-bin:
  stage: test
  script:
    - make bin
    - ci/check-fips.sh bin/*

build-bin-windows:
  image: nsx-ujo-docker-local.packages.vcfd.broadcom.net/microsoft/golang:1.23-fips-bookworm-e96f8bcd
  stage: test
  script:
    - make windows-bin
