image: nsx-ujo-docker-local.packages.vcfd.broadcom.net/antrea/golang:1.21.7

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache
  DOCKER_BUILDKIT: 1
  NO_PULL: 1

default:
  before_script:
    - |
      apt update
      apt install -y jq
      export GO_VERSION=$(cat build/images/deps/go-version)
      echo "Ensuring go version"
      mkdir -p ~/.local/go/
      export GOPATH=~/.local/go/
      export GO_VERSION_FULL=$(curl "https://go.dev/dl/?mode=json&include=all" | jq --arg go_version_prefix go${GO_VERSION} -r '. | map(select(. | .version | startswith($go_version_prefix)))|first|.version')
      go install golang.org/dl/${GO_VERSION_FULL}@latest
      ${GOPATH}/bin/${GO_VERSION_FULL} download
      ln -sf ${GOPATH}/bin/${GO_VERSION_FULL} ${GOPATH}/bin/go
      export PATH=${GOPATH}/bin:$PATH
      echo "Using $(go version)"

stages:
  - lint
  - test

test-unit:
  stage: test
  script:
    - echo "Check if we can build e2e tests"
    - go test -c  -o /dev/null antrea.io/antrea/test/e2e
    - echo "Run unit tests"
    - make test-unit

check-codegen:
  before_script: []
  image: dockerhub.artifactory.vcfd.broadcom.net/antrea/codegen:kubernetes-1.29.2-build.2
  stage: lint
  script:
    - ./ci/check-codegen.sh

check-manifest:
  before_script: []
  stage: lint
  script:
    - ./ci/check-manifest.sh

# TODO: Enable Golang lint check and fix the lint errors
#check-lint:
#  stage: lint
#  script:
#    - make golangci

build-bin:
  stage: test
  script:
    - make bin
    - make windows-bin
