LINUX_HOSTTYPE = 'linux-rocky8-vm-fw'

ANTREA_INTERWORKING_BRANCH = "release-1.2"
ANTREA_INTERWORKING_BUILDTYPE = "release"
ANTREA_INTERWORKING_FILES = {
    LINUX_HOSTTYPE: [
        r'publish/.*',
    ]
}

CAYMAN_ANTREA_BRANCH = "vmware-2.2.0+vmware.2"
CAYMAN_ANTREA_BUILDTYPE = "release"
CAYMAN_ANTREA_FILES = {
    LINUX_HOSTTYPE: [
        r'publish/.*',
    ]
}

CAYMAN_ANTREA_OPERATOR_FOR_KUBERNETES_BRANCH = "vmware-2.1.0+vmware.3"
CAYMAN_ANTREA_OPERATOR_FOR_KUBERNETES_BUILDTYPE = "release"
CAYMAN_ANTREA_OPERATOR_FOR_KUBERNETES_FILES = {
    LINUX_HOSTTYPE: [
        r'publish/.*',
    ]
}

NSX_MANAGEMENT_PROXY_PACKAGE_BRANCH = "release-0.2"
NSX_MANAGEMENT_PROXY_PACKAGE_BUILDTYPE = "release"
NSX_MANAGEMENT_PROXY_PACKAGE_FILES = {
    LINUX_HOSTTYPE: [
        r'publish/.*',
    ]
}
