// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// NSXRegistrationLister helps list NSXRegistrations.
// All objects returned here must be treated as read-only.
type NSXRegistrationLister interface {
	// List lists all NSXRegistrations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NSXRegistration, err error)
	// Get retrieves the NSXRegistration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NSXRegistration, error)
	NSXRegistrationListerExpansion
}

// nSXRegistrationLister implements the NSXRegistrationLister interface.
type nSXRegistrationLister struct {
	listers.ResourceIndexer[*v1alpha1.NSXRegistration]
}

// NewNSXRegistrationLister returns a new NSXRegistrationLister.
func NewNSXRegistrationLister(indexer cache.Indexer) NSXRegistrationLister {
	return &nSXRegistrationLister{listers.New[*v1alpha1.NSXRegistration](indexer, v1alpha1.Resource("nsxregistration"))}
}
