// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	crdv1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	versioned "antrea.io/antrea/pkg/client/clientset/versioned"
	internalinterfaces "antrea.io/antrea/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "antrea.io/antrea/pkg/client/listers/crd/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressEntitlementInformer provides access to a shared informer and lister for
// EgressEntitlements.
type EgressEntitlementInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.EgressEntitlementLister
}

type egressEntitlementInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEgressEntitlementInformer constructs a new informer for EgressEntitlement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressEntitlementInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressEntitlementInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEgressEntitlementInformer constructs a new informer for EgressEntitlement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressEntitlementInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().EgressEntitlements().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().EgressEntitlements().Watch(context.TODO(), options)
			},
		},
		&crdv1beta1.EgressEntitlement{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressEntitlementInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressEntitlementInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressEntitlementInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdv1beta1.EgressEntitlement{}, f.defaultInformer)
}

func (f *egressEntitlementInformer) Lister() v1beta1.EgressEntitlementLister {
	return v1beta1.NewEgressEntitlementLister(f.Informer().GetIndexer())
}
