// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	crdv1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	versioned "antrea.io/antrea/pkg/client/clientset/versioned"
	internalinterfaces "antrea.io/antrea/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "antrea.io/antrea/pkg/client/listers/crd/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressEntitlementBindingInformer provides access to a shared informer and lister for
// EgressEntitlementBindings.
type EgressEntitlementBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.EgressEntitlementBindingLister
}

type egressEntitlementBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEgressEntitlementBindingInformer constructs a new informer for EgressEntitlementBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressEntitlementBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressEntitlementBindingInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEgressEntitlementBindingInformer constructs a new informer for EgressEntitlementBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressEntitlementBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().EgressEntitlementBindings().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().EgressEntitlementBindings().Watch(context.TODO(), options)
			},
		},
		&crdv1beta1.EgressEntitlementBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressEntitlementBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressEntitlementBindingInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressEntitlementBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdv1beta1.EgressEntitlementBinding{}, f.defaultInformer)
}

func (f *egressEntitlementBindingInformer) Lister() v1beta1.EgressEntitlementBindingLister {
	return v1beta1.NewEgressEntitlementBindingLister(f.Informer().GetIndexer())
}
