// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIDPSPolicies implements IDPSPolicyInterface
type FakeIDPSPolicies struct {
	Fake *FakeTanzuCrdV1alpha1
}

var idpspoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("idpspolicies")

var idpspoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("IDPSPolicy")

// Get takes name of the iDPSPolicy, and returns the corresponding iDPSPolicy object, and an error if there is any.
func (c *FakeIDPSPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IDPSPolicy, err error) {
	emptyResult := &v1alpha1.IDPSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(idpspoliciesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSPolicy), err
}

// List takes label and field selectors, and returns the list of IDPSPolicies that match those selectors.
func (c *FakeIDPSPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IDPSPolicyList, err error) {
	emptyResult := &v1alpha1.IDPSPolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(idpspoliciesResource, idpspoliciesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IDPSPolicyList{ListMeta: obj.(*v1alpha1.IDPSPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.IDPSPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iDPSPolicies.
func (c *FakeIDPSPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(idpspoliciesResource, opts))
}

// Create takes the representation of a iDPSPolicy and creates it.  Returns the server's representation of the iDPSPolicy, and an error, if there is any.
func (c *FakeIDPSPolicies) Create(ctx context.Context, iDPSPolicy *v1alpha1.IDPSPolicy, opts v1.CreateOptions) (result *v1alpha1.IDPSPolicy, err error) {
	emptyResult := &v1alpha1.IDPSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(idpspoliciesResource, iDPSPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSPolicy), err
}

// Update takes the representation of a iDPSPolicy and updates it. Returns the server's representation of the iDPSPolicy, and an error, if there is any.
func (c *FakeIDPSPolicies) Update(ctx context.Context, iDPSPolicy *v1alpha1.IDPSPolicy, opts v1.UpdateOptions) (result *v1alpha1.IDPSPolicy, err error) {
	emptyResult := &v1alpha1.IDPSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(idpspoliciesResource, iDPSPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSPolicy), err
}

// Delete takes name of the iDPSPolicy and deletes it. Returns an error if one occurs.
func (c *FakeIDPSPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(idpspoliciesResource, name, opts), &v1alpha1.IDPSPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIDPSPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(idpspoliciesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IDPSPolicyList{})
	return err
}

// Patch applies the patch and returns the patched iDPSPolicy.
func (c *FakeIDPSPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IDPSPolicy, err error) {
	emptyResult := &v1alpha1.IDPSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(idpspoliciesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSPolicy), err
}
