// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNSXRegistrations implements NSXRegistrationInterface
type FakeNSXRegistrations struct {
	Fake *FakeTanzuCrdV1alpha1
}

var nsxregistrationsResource = v1alpha1.SchemeGroupVersion.WithResource("nsxregistrations")

var nsxregistrationsKind = v1alpha1.SchemeGroupVersion.WithKind("NSXRegistration")

// Get takes name of the nSXRegistration, and returns the corresponding nSXRegistration object, and an error if there is any.
func (c *FakeNSXRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NSXRegistration, err error) {
	emptyResult := &v1alpha1.NSXRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(nsxregistrationsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NSXRegistration), err
}

// List takes label and field selectors, and returns the list of NSXRegistrations that match those selectors.
func (c *FakeNSXRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NSXRegistrationList, err error) {
	emptyResult := &v1alpha1.NSXRegistrationList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(nsxregistrationsResource, nsxregistrationsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NSXRegistrationList{ListMeta: obj.(*v1alpha1.NSXRegistrationList).ListMeta}
	for _, item := range obj.(*v1alpha1.NSXRegistrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nSXRegistrations.
func (c *FakeNSXRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(nsxregistrationsResource, opts))
}

// Create takes the representation of a nSXRegistration and creates it.  Returns the server's representation of the nSXRegistration, and an error, if there is any.
func (c *FakeNSXRegistrations) Create(ctx context.Context, nSXRegistration *v1alpha1.NSXRegistration, opts v1.CreateOptions) (result *v1alpha1.NSXRegistration, err error) {
	emptyResult := &v1alpha1.NSXRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(nsxregistrationsResource, nSXRegistration, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NSXRegistration), err
}

// Update takes the representation of a nSXRegistration and updates it. Returns the server's representation of the nSXRegistration, and an error, if there is any.
func (c *FakeNSXRegistrations) Update(ctx context.Context, nSXRegistration *v1alpha1.NSXRegistration, opts v1.UpdateOptions) (result *v1alpha1.NSXRegistration, err error) {
	emptyResult := &v1alpha1.NSXRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(nsxregistrationsResource, nSXRegistration, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NSXRegistration), err
}

// Delete takes name of the nSXRegistration and deletes it. Returns an error if one occurs.
func (c *FakeNSXRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(nsxregistrationsResource, name, opts), &v1alpha1.NSXRegistration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNSXRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(nsxregistrationsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NSXRegistrationList{})
	return err
}

// Patch applies the patch and returns the patched nSXRegistration.
func (c *FakeNSXRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NSXRegistration, err error) {
	emptyResult := &v1alpha1.NSXRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(nsxregistrationsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NSXRegistration), err
}
