// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIDPSSignatureProviderInfos implements IDPSSignatureProviderInfoInterface
type FakeIDPSSignatureProviderInfos struct {
	Fake *FakeTanzuCrdV1alpha1
}

var idpssignatureproviderinfosResource = v1alpha1.SchemeGroupVersion.WithResource("idpssignatureproviderinfos")

var idpssignatureproviderinfosKind = v1alpha1.SchemeGroupVersion.WithKind("IDPSSignatureProviderInfo")

// Get takes name of the iDPSSignatureProviderInfo, and returns the corresponding iDPSSignatureProviderInfo object, and an error if there is any.
func (c *FakeIDPSSignatureProviderInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IDPSSignatureProviderInfo, err error) {
	emptyResult := &v1alpha1.IDPSSignatureProviderInfo{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(idpssignatureproviderinfosResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSSignatureProviderInfo), err
}

// List takes label and field selectors, and returns the list of IDPSSignatureProviderInfos that match those selectors.
func (c *FakeIDPSSignatureProviderInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IDPSSignatureProviderInfoList, err error) {
	emptyResult := &v1alpha1.IDPSSignatureProviderInfoList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(idpssignatureproviderinfosResource, idpssignatureproviderinfosKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IDPSSignatureProviderInfoList{ListMeta: obj.(*v1alpha1.IDPSSignatureProviderInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.IDPSSignatureProviderInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iDPSSignatureProviderInfos.
func (c *FakeIDPSSignatureProviderInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(idpssignatureproviderinfosResource, opts))
}

// Create takes the representation of a iDPSSignatureProviderInfo and creates it.  Returns the server's representation of the iDPSSignatureProviderInfo, and an error, if there is any.
func (c *FakeIDPSSignatureProviderInfos) Create(ctx context.Context, iDPSSignatureProviderInfo *v1alpha1.IDPSSignatureProviderInfo, opts v1.CreateOptions) (result *v1alpha1.IDPSSignatureProviderInfo, err error) {
	emptyResult := &v1alpha1.IDPSSignatureProviderInfo{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(idpssignatureproviderinfosResource, iDPSSignatureProviderInfo, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSSignatureProviderInfo), err
}

// Update takes the representation of a iDPSSignatureProviderInfo and updates it. Returns the server's representation of the iDPSSignatureProviderInfo, and an error, if there is any.
func (c *FakeIDPSSignatureProviderInfos) Update(ctx context.Context, iDPSSignatureProviderInfo *v1alpha1.IDPSSignatureProviderInfo, opts v1.UpdateOptions) (result *v1alpha1.IDPSSignatureProviderInfo, err error) {
	emptyResult := &v1alpha1.IDPSSignatureProviderInfo{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(idpssignatureproviderinfosResource, iDPSSignatureProviderInfo, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSSignatureProviderInfo), err
}

// Delete takes name of the iDPSSignatureProviderInfo and deletes it. Returns an error if one occurs.
func (c *FakeIDPSSignatureProviderInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(idpssignatureproviderinfosResource, name, opts), &v1alpha1.IDPSSignatureProviderInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIDPSSignatureProviderInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(idpssignatureproviderinfosResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IDPSSignatureProviderInfoList{})
	return err
}

// Patch applies the patch and returns the patched iDPSSignatureProviderInfo.
func (c *FakeIDPSSignatureProviderInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IDPSSignatureProviderInfo, err error) {
	emptyResult := &v1alpha1.IDPSSignatureProviderInfo{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(idpssignatureproviderinfosResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IDPSSignatureProviderInfo), err
}
