// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/antrea/pkg/client/clientset/versioned/typed/tanzucrd/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTanzuCrdV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTanzuCrdV1alpha1) IDPSPolicies() v1alpha1.IDPSPolicyInterface {
	return &FakeIDPSPolicies{c}
}

func (c *FakeTanzuCrdV1alpha1) IDPSSignatureProviderInfos() v1alpha1.IDPSSignatureProviderInfoInterface {
	return &FakeIDPSSignatureProviderInfos{c}
}

func (c *FakeTanzuCrdV1alpha1) NSXRegistrations() v1alpha1.NSXRegistrationInterface {
	return &FakeNSXRegistrations{c}
}

func (c *FakeTanzuCrdV1alpha1) TierEntitlements() v1alpha1.TierEntitlementInterface {
	return &FakeTierEntitlements{c}
}

func (c *FakeTanzuCrdV1alpha1) TierEntitlementBindings() v1alpha1.TierEntitlementBindingInterface {
	return &FakeTierEntitlementBindings{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTanzuCrdV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
