// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IDPSPoliciesGetter has a method to return a IDPSPolicyInterface.
// A group's client should implement this interface.
type IDPSPoliciesGetter interface {
	IDPSPolicies() IDPSPolicyInterface
}

// IDPSPolicyInterface has methods to work with IDPSPolicy resources.
type IDPSPolicyInterface interface {
	Create(ctx context.Context, iDPSPolicy *v1alpha1.IDPSPolicy, opts v1.CreateOptions) (*v1alpha1.IDPSPolicy, error)
	Update(ctx context.Context, iDPSPolicy *v1alpha1.IDPSPolicy, opts v1.UpdateOptions) (*v1alpha1.IDPSPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IDPSPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IDPSPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IDPSPolicy, err error)
	IDPSPolicyExpansion
}

// iDPSPolicies implements IDPSPolicyInterface
type iDPSPolicies struct {
	*gentype.ClientWithList[*v1alpha1.IDPSPolicy, *v1alpha1.IDPSPolicyList]
}

// newIDPSPolicies returns a IDPSPolicies
func newIDPSPolicies(c *TanzuCrdV1alpha1Client) *iDPSPolicies {
	return &iDPSPolicies{
		gentype.NewClientWithList[*v1alpha1.IDPSPolicy, *v1alpha1.IDPSPolicyList](
			"idpspolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.IDPSPolicy { return &v1alpha1.IDPSPolicy{} },
			func() *v1alpha1.IDPSPolicyList { return &v1alpha1.IDPSPolicyList{} }),
	}
}
