// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NSXRegistrationsGetter has a method to return a NSXRegistrationInterface.
// A group's client should implement this interface.
type NSXRegistrationsGetter interface {
	NSXRegistrations() NSXRegistrationInterface
}

// NSXRegistrationInterface has methods to work with NSXRegistration resources.
type NSXRegistrationInterface interface {
	Create(ctx context.Context, nSXRegistration *v1alpha1.NSXRegistration, opts v1.CreateOptions) (*v1alpha1.NSXRegistration, error)
	Update(ctx context.Context, nSXRegistration *v1alpha1.NSXRegistration, opts v1.UpdateOptions) (*v1alpha1.NSXRegistration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NSXRegistration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NSXRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NSXRegistration, err error)
	NSXRegistrationExpansion
}

// nSXRegistrations implements NSXRegistrationInterface
type nSXRegistrations struct {
	*gentype.ClientWithList[*v1alpha1.NSXRegistration, *v1alpha1.NSXRegistrationList]
}

// newNSXRegistrations returns a NSXRegistrations
func newNSXRegistrations(c *TanzuCrdV1alpha1Client) *nSXRegistrations {
	return &nSXRegistrations{
		gentype.NewClientWithList[*v1alpha1.NSXRegistration, *v1alpha1.NSXRegistrationList](
			"nsxregistrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.NSXRegistration { return &v1alpha1.NSXRegistration{} },
			func() *v1alpha1.NSXRegistrationList { return &v1alpha1.NSXRegistrationList{} }),
	}
}
