// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TierEntitlementsGetter has a method to return a TierEntitlementInterface.
// A group's client should implement this interface.
type TierEntitlementsGetter interface {
	TierEntitlements() TierEntitlementInterface
}

// TierEntitlementInterface has methods to work with TierEntitlement resources.
type TierEntitlementInterface interface {
	Create(ctx context.Context, tierEntitlement *v1alpha1.TierEntitlement, opts v1.CreateOptions) (*v1alpha1.TierEntitlement, error)
	Update(ctx context.Context, tierEntitlement *v1alpha1.TierEntitlement, opts v1.UpdateOptions) (*v1alpha1.TierEntitlement, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TierEntitlement, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TierEntitlementList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TierEntitlement, err error)
	TierEntitlementExpansion
}

// tierEntitlements implements TierEntitlementInterface
type tierEntitlements struct {
	*gentype.ClientWithList[*v1alpha1.TierEntitlement, *v1alpha1.TierEntitlementList]
}

// newTierEntitlements returns a TierEntitlements
func newTierEntitlements(c *TanzuCrdV1alpha1Client) *tierEntitlements {
	return &tierEntitlements{
		gentype.NewClientWithList[*v1alpha1.TierEntitlement, *v1alpha1.TierEntitlementList](
			"tierentitlements",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.TierEntitlement { return &v1alpha1.TierEntitlement{} },
			func() *v1alpha1.TierEntitlementList { return &v1alpha1.TierEntitlementList{} }),
	}
}
