// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FlowExporterTargetsGetter has a method to return a FlowExporterTargetInterface.
// A group's client should implement this interface.
type FlowExporterTargetsGetter interface {
	FlowExporterTargets() FlowExporterTargetInterface
}

// FlowExporterTargetInterface has methods to work with FlowExporterTarget resources.
type FlowExporterTargetInterface interface {
	Create(ctx context.Context, flowExporterTarget *v1beta1.FlowExporterTarget, opts v1.CreateOptions) (*v1beta1.FlowExporterTarget, error)
	Update(ctx context.Context, flowExporterTarget *v1beta1.FlowExporterTarget, opts v1.UpdateOptions) (*v1beta1.FlowExporterTarget, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, flowExporterTarget *v1beta1.FlowExporterTarget, opts v1.UpdateOptions) (*v1beta1.FlowExporterTarget, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FlowExporterTarget, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FlowExporterTargetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FlowExporterTarget, err error)
	FlowExporterTargetExpansion
}

// flowExporterTargets implements FlowExporterTargetInterface
type flowExporterTargets struct {
	*gentype.ClientWithList[*v1beta1.FlowExporterTarget, *v1beta1.FlowExporterTargetList]
}

// newFlowExporterTargets returns a FlowExporterTargets
func newFlowExporterTargets(c *CrdV1beta1Client) *flowExporterTargets {
	return &flowExporterTargets{
		gentype.NewClientWithList[*v1beta1.FlowExporterTarget, *v1beta1.FlowExporterTargetList](
			"flowexportertargets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.FlowExporterTarget { return &v1beta1.FlowExporterTarget{} },
			func() *v1beta1.FlowExporterTargetList { return &v1beta1.FlowExporterTargetList{} }),
	}
}
