// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	tanzucrdv1alpha1 "antrea.io/antrea/pkg/apis/tanzucrd/v1alpha1"
	versioned "antrea.io/antrea/pkg/client/clientset/versioned"
	internalinterfaces "antrea.io/antrea/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "antrea.io/antrea/pkg/client/listers/tanzucrd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NSXRegistrationInformer provides access to a shared informer and lister for
// NSXRegistrations.
type NSXRegistrationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NSXRegistrationLister
}

type nSXRegistrationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNSXRegistrationInformer constructs a new informer for NSXRegistration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNSXRegistrationInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNSXRegistrationInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNSXRegistrationInformer constructs a new informer for NSXRegistration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNSXRegistrationInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TanzuCrdV1alpha1().NSXRegistrations().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TanzuCrdV1alpha1().NSXRegistrations().Watch(context.TODO(), options)
			},
		},
		&tanzucrdv1alpha1.NSXRegistration{},
		resyncPeriod,
		indexers,
	)
}

func (f *nSXRegistrationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNSXRegistrationInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nSXRegistrationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tanzucrdv1alpha1.NSXRegistration{}, f.defaultInformer)
}

func (f *nSXRegistrationInformer) Lister() v1alpha1.NSXRegistrationLister {
	return v1alpha1.NewNSXRegistrationLister(f.Informer().GetIndexer())
}
