// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "antrea.io/antrea/pkg/apis/system/v1beta1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// NodeCPUInfosGetter has a method to return a NodeCPUInfoInterface.
// A group's client should implement this interface.
type NodeCPUInfosGetter interface {
	NodeCPUInfos() NodeCPUInfoInterface
}

// NodeCPUInfoInterface has methods to work with NodeCPUInfo resources.
type NodeCPUInfoInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.NodeCPUInfo, error)
	NodeCPUInfoExpansion
}

// nodeCPUInfos implements NodeCPUInfoInterface
type nodeCPUInfos struct {
	*gentype.Client[*v1beta1.NodeCPUInfo]
}

// newNodeCPUInfos returns a NodeCPUInfos
func newNodeCPUInfos(c *SystemV1beta1Client) *nodeCPUInfos {
	return &nodeCPUInfos{
		gentype.NewClient[*v1beta1.NodeCPUInfo](
			"nodecpuinfos",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.NodeCPUInfo { return &v1beta1.NodeCPUInfo{} }),
	}
}
