FROM $(REGISTRY)/$(GOBUILD_NSBU_DOCKER_IMAGES_BUILDID)/ubuntu16.04-alias as cni-binaries

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget ca-certificates

# Leading dot is required for the tar command below
ENV CNI_PLUGINS="./host-local ./loopback ./portmap"

RUN mkdir -p /opt/cni/bin && \
    wget -q -O - https://dl.k8s.io/network-plugins/cni-plugins-amd64-v0.7.5.tgz | tar xz -C /opt/cni/bin $CNI_PLUGINS

FROM $(REGISTRY)/$(GOBUILD_NSBU_DOCKER_IMAGES_BUILDID)/ubuntu16.04-alias as ubuntu

COPY --from=cni-binaries /opt/cni/bin /opt/cni/bin

LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
LABEL description="A Docker image to deploy the Antrea CNI. Requires the Antrea binaries to be built prior to building the image."

USER root
