// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressEntitlements implements EgressEntitlementInterface
type FakeEgressEntitlements struct {
	Fake *FakeCrdV1beta1
}

var egressentitlementsResource = v1beta1.SchemeGroupVersion.WithResource("egressentitlements")

var egressentitlementsKind = v1beta1.SchemeGroupVersion.WithKind("EgressEntitlement")

// Get takes name of the egressEntitlement, and returns the corresponding egressEntitlement object, and an error if there is any.
func (c *FakeEgressEntitlements) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EgressEntitlement, err error) {
	emptyResult := &v1beta1.EgressEntitlement{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(egressentitlementsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EgressEntitlement), err
}

// List takes label and field selectors, and returns the list of EgressEntitlements that match those selectors.
func (c *FakeEgressEntitlements) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EgressEntitlementList, err error) {
	emptyResult := &v1beta1.EgressEntitlementList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(egressentitlementsResource, egressentitlementsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.EgressEntitlementList{ListMeta: obj.(*v1beta1.EgressEntitlementList).ListMeta}
	for _, item := range obj.(*v1beta1.EgressEntitlementList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressEntitlements.
func (c *FakeEgressEntitlements) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(egressentitlementsResource, opts))
}

// Create takes the representation of a egressEntitlement and creates it.  Returns the server's representation of the egressEntitlement, and an error, if there is any.
func (c *FakeEgressEntitlements) Create(ctx context.Context, egressEntitlement *v1beta1.EgressEntitlement, opts v1.CreateOptions) (result *v1beta1.EgressEntitlement, err error) {
	emptyResult := &v1beta1.EgressEntitlement{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(egressentitlementsResource, egressEntitlement, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EgressEntitlement), err
}

// Update takes the representation of a egressEntitlement and updates it. Returns the server's representation of the egressEntitlement, and an error, if there is any.
func (c *FakeEgressEntitlements) Update(ctx context.Context, egressEntitlement *v1beta1.EgressEntitlement, opts v1.UpdateOptions) (result *v1beta1.EgressEntitlement, err error) {
	emptyResult := &v1beta1.EgressEntitlement{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(egressentitlementsResource, egressEntitlement, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EgressEntitlement), err
}

// Delete takes name of the egressEntitlement and deletes it. Returns an error if one occurs.
func (c *FakeEgressEntitlements) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(egressentitlementsResource, name, opts), &v1beta1.EgressEntitlement{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressEntitlements) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(egressentitlementsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.EgressEntitlementList{})
	return err
}

// Patch applies the patch and returns the patched egressEntitlement.
func (c *FakeEgressEntitlements) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EgressEntitlement, err error) {
	emptyResult := &v1beta1.EgressEntitlement{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(egressentitlementsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EgressEntitlement), err
}
