#!/bin/bash
set -xe
# refer to
# https://confluence.eng.vmware.com/display/OSMUserGuide/VM+%28vApp+Virtual+Machines%29+or+Containers?src=contextnavpagetreemode
# https://confluence.eng.vmware.com/display/CNA/Cascade+OSSTP

RELEASE_VERSION=1.9.0

echo Scann OS packages for Antrea commercial release $RELEASE_VERSION

if [ -z "$1" ]; then
  # Need to manually create package ct-track-rhel9 on https://osm.eng.vmware.com/ first
  echo Usage: $0 BaseOSTicketNum
  exit 1
else
  CT_TRACKER="$1"
fi

# Antrea operator uses minimal UBI image, it's recommended to install yum manually following below steps befor run this script.
# Download yum and all its dependencies with `repotrack`.
#### yum -y install yum-utils && repotrack yum
# Copy all packages into antrea-operator container.
#### docker cp *.rpm container_id:/dest_dir
# Install all rpm packages in antrea-operator container.
#### rpm -Uvh --force --nodeps *.rpm

echo ============================================================
echo Make sure run inside container created from the docker image
echo ============================================================
echo
echo ====== NOTE ======
echo For operator image, need to override the entrypoint and user in docker run command
echo Example: docker run -idt --rm --name operator -u root --entrypoint bash localhost:5000/vmware.io/antrea/antrea-operator:vmware-1.7.0

rm -rf /etc/yum.repos.d/*
cat > /etc/yum.repos.d/CentOS.repo <<EOF
[AppStream]
name=CentOS-9 - AppStream
baseurl=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/
gpgcheck=0
enabled=1

[BaseOS]
name=CentOS-9 - Base
baseurl=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/
gpgcheck=0
enabled=1

[crb]
name=CentOS Linux 9 - CRB
baseurl=https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/
gpgcheck=0
enabled=1


[Appstream-source]
name= Centos 9 stream (Source RPMs) - Appstream-source
baseurl = https://mirror.stream.centos.org/9-stream/AppStream/source/tree/
enabled = 1
gpgcheck = 0


[BaseOS-source]
name= Centos 9 stream (Source RPMs) - BaseOS-source
baseurl = https://mirror.stream.centos.org/9-stream/BaseOS/source/tree/
enabled = 1
gpgcheck = 0

[crb]
name= Centos 9 stream (Source RPMs) - CRB-source
baseurl = https://mirror.stream.centos.org/9-stream/CRB/source/tree/
enabled = 1
gpgcheck = 0
EOF
curl https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official -o /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
# if ubi base image is ubi-minimal, there would be no subscription-manager and yum installed
subscription-manager config --rhsm.manage_repos=0 || true
yum --help || microdnf install yum
yum clean all -y
yum makecache

# Mannually install if failed
yum install -y unzip yum-utils || true

mkdir -p osstpclients
cd osstpclients
curl -LO https://artifactory.eng.vmware.com/artifactory/osm-client-generic-local/osstpclients3_2023-05-18.zip
unzip osstpclients3_2023-05-18.zip
cd bin

./vm-inventory.sh -s rpm rhel9

cat > /tmp/osm-apykey <<EOF
zhengshengz@vmware.com 3d8a2d9af7542d4bf4901fd5c7b72d47ee218872
EOF
./client_executables/linux-amd64/osstp-load --baseos-ct-tracker "${CT_TRACKER}" --baseos-append --noinput -A /tmp/osm-apykey -R "Antrea/${RELEASE_VERSION}" --baseos-srcdir ~/source osstpmgt.yaml | tee oss.log

source_packages="$(cat oss.log | grep 'No BaseOS package available for' | awk '{print $8}' | awk -F ':' '{print $3}')"

mkdir -p ../../source
cd ../../source
for pkg in ${source_packages} ; do
  dnf download --source --downloaddir=. "${pkg}" || true
done

cd ../osstpclients

# https://confluence.eng.vmware.com/display/public/OSMUserGuide/BaseOS+Packages#BaseOSPackages-InventoryingPackages:RPMBased
rm -f bin/osstpmgt.yaml
# TODO(zhengsheng) osstpmgt.yaml generated by osdist-inventory contains binary data, and osstp-load cannot recognize it.
# Need a dedicate process for converting binary data to string. This is left for TODO item.
./bin/client_executables/linux-amd64/osdist-inventory -D ../source -T rhel9
mv osstpmgt.yaml bin/
if [ -f bin/osstpmgt.yaml ]; then
  ./bin/client_executables/linux-amd64/osstp-load --baseos-ct-tracker "${CT_TRACKER}" --baseos-append --noinput --debug -A /tmp/osm-apykey -R "Antrea/${RELEASE_VERSION}" --baseos-srcdir ../source bin/osstpmgt.yaml || true
fi

rm -f /tmp/osm-apykey
