// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// EgressEntitlementBindingLister helps list EgressEntitlementBindings.
// All objects returned here must be treated as read-only.
type EgressEntitlementBindingLister interface {
	// List lists all EgressEntitlementBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.EgressEntitlementBinding, err error)
	// Get retrieves the EgressEntitlementBinding from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.EgressEntitlementBinding, error)
	EgressEntitlementBindingListerExpansion
}

// egressEntitlementBindingLister implements the EgressEntitlementBindingLister interface.
type egressEntitlementBindingLister struct {
	listers.ResourceIndexer[*v1beta1.EgressEntitlementBinding]
}

// NewEgressEntitlementBindingLister returns a new EgressEntitlementBindingLister.
func NewEgressEntitlementBindingLister(indexer cache.Indexer) EgressEntitlementBindingLister {
	return &egressEntitlementBindingLister{listers.New[*v1beta1.EgressEntitlementBinding](indexer, v1beta1.Resource("egressentitlementbinding"))}
}
