// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/pkg/cloudprovider (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/cloudprovider/testing/mock_cloudprovider.go -package testing antrea.io/antrea/pkg/cloudprovider Interface
//

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// AssignIPToNode mocks base method.
func (m *MockInterface) AssignIPToNode(ip string, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignIPToNode", ip, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignIPToNode indicates an expected call of AssignIPToNode.
func (mr *MockInterfaceMockRecorder) AssignIPToNode(ip, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignIPToNode", reflect.TypeOf((*MockInterface)(nil).AssignIPToNode), ip, node)
}

// GetIPsByNode mocks base method.
func (m *MockInterface) GetIPsByNode(node *v1.Node) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPsByNode", node)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPsByNode indicates an expected call of GetIPsByNode.
func (mr *MockInterfaceMockRecorder) GetIPsByNode(node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPsByNode", reflect.TypeOf((*MockInterface)(nil).GetIPsByNode), node)
}

// GetMaxIPsByInstanceType mocks base method.
func (m *MockInterface) GetMaxIPsByInstanceType(instanceType string) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxIPsByInstanceType", instanceType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMaxIPsByInstanceType indicates an expected call of GetMaxIPsByInstanceType.
func (mr *MockInterfaceMockRecorder) GetMaxIPsByInstanceType(instanceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxIPsByInstanceType", reflect.TypeOf((*MockInterface)(nil).GetMaxIPsByInstanceType), instanceType)
}

// UnassignIPToNode mocks base method.
func (m *MockInterface) UnassignIPToNode(ip string, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignIPToNode", ip, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignIPToNode indicates an expected call of UnassignIPToNode.
func (mr *MockInterfaceMockRecorder) UnassignIPToNode(ip, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignIPToNode", reflect.TypeOf((*MockInterface)(nil).UnassignIPToNode), ip, node)
}
